#!/usr/bin/env python3
"""Read-only Workflow MCP telemetry analyzer.

Reads privacy-safe calls.jsonl telemetry and writes/prints a compact Markdown
report. Raw prompts are never logged or required by the analyzer.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import statistics
from collections import Counter
from pathlib import Path
from typing import Any

TASK_DIR = Path(__file__).resolve().parent
DEFAULT_CALLS = Path.home() / "Projects/workflow-mcp/logs/calls.jsonl"
DEFAULT_REPORT_DIR = Path.home() / "Obsidian/Work/Daily/Lint"


def _load_rows(path: Path) -> tuple[list[dict[str, Any]], int]:
    rows: list[dict[str, Any]] = []
    malformed = 0
    if not path.exists():
        return rows, 0
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        if not line.strip():
            continue
        try:
            item = json.loads(line)
        except json.JSONDecodeError:
            malformed += 1
            continue
        if isinstance(item, dict):
            rows.append(item)
        else:
            malformed += 1
    return rows, malformed


def _pct(values: list[float], percentile: float) -> float:
    if not values:
        return 0.0
    ordered = sorted(values)
    index = min(len(ordered) - 1, max(0, round((percentile / 100) * (len(ordered) - 1))))
    return ordered[index]


def _counter_table(title: str, counter: Counter[Any], limit: int = 20) -> list[str]:
    lines = [f"### {title}", "", "| Value | Count |", "|---|---:|"]
    if not counter:
        lines.append("| _none_ | 0 |")
    else:
        for value, count in counter.most_common(limit):
            lines.append(f"| `{value}` | {count} |")
    lines.append("")
    return lines


def build_report(rows: list[dict[str, Any]], malformed: int, calls_path: Path) -> str:
    now = dt.datetime.now().astimezone()
    durations = [float(row.get("duration_ms", 0) or 0) for row in rows]
    successes = Counter(bool(row.get("success")) for row in rows)
    errors = Counter(row.get("exception_type") for row in rows if not row.get("success"))
    tools = Counter(row.get("tool", "unknown") for row in rows)
    buckets = Counter(row.get("bucket") for row in rows if row.get("bucket"))
    versions = Counter(row.get("service_version") for row in rows if row.get("service_version"))
    overrides = Counter(
        f"{row.get('override_from')}->{row.get('override_to')}"
        for row in rows
        if row.get("override_from")
    )
    ambiguity_count = sum(1 for row in rows if row.get("ambiguity") is True)
    guard_count = sum(1 for row in rows if row.get("reasoning_guard_required") is True)
    delegated_count = sum(1 for row in rows if row.get("should_delegate") is True)
    candidate_counts = [int(row.get("candidate_count", 0) or 0) for row in rows if "candidate_count" in row]
    checklist_counts = [int(row.get("checklist_count", 0) or 0) for row in rows if "checklist_count" in row]
    slowest = sorted(rows, key=lambda row: float(row.get("duration_ms", 0) or 0), reverse=True)[:10]

    def rate(count: int) -> str:
        return f"{(count / len(rows) * 100):.1f}%" if rows else "0.0%"

    lines = [
        f"# Workflow MCP metrics — {now.date().isoformat()}",
        "",
        "Generated by `scheduled-tasks/workflow-mcp/analyze_metrics.py` from privacy-safe telemetry.",
        "",
        "## Summary",
        "",
        f"- Source: `{calls_path}`",
        f"- Rows: {len(rows)}",
        f"- Malformed rows: {malformed}",
        f"- Success: {successes.get(True, 0)} ({rate(successes.get(True, 0))})",
        f"- Errors: {successes.get(False, 0)} ({rate(successes.get(False, 0))})",
        f"- Ambiguous classifications: {ambiguity_count} ({rate(ambiguity_count)})",
        f"- Reasoning guard required: {guard_count} ({rate(guard_count)})",
        f"- Delegation suggested: {delegated_count} ({rate(delegated_count)})",
        "",
        "## Latency",
        "",
        f"- Avg ms: {statistics.mean(durations):.2f}" if durations else "- Avg ms: 0.00",
        f"- P50 ms: {statistics.median(durations):.2f}" if durations else "- P50 ms: 0.00",
        f"- P95 ms: {_pct(durations, 95):.2f}",
        f"- Max ms: {max(durations):.2f}" if durations else "- Max ms: 0.00",
        "",
        "## Distributions",
        "",
        f"- Candidate count avg: {statistics.mean(candidate_counts):.2f}" if candidate_counts else "- Candidate count avg: n/a",
        f"- Checklist count avg: {statistics.mean(checklist_counts):.2f}" if checklist_counts else "- Checklist count avg: n/a",
        "",
    ]
    lines.extend(_counter_table("Tools", tools))
    lines.extend(_counter_table("Buckets", buckets))
    lines.extend(_counter_table("Errors", errors))
    lines.extend(_counter_table("Classifier overrides (mine these into evals/golden.jsonl)", overrides))
    lines.extend(_counter_table("Service versions", versions))
    lines.extend(["### Slowest calls", "", "| Tool | Duration ms | Success | Bucket | Version |", "|---|---:|---|---|---|"])
    for row in slowest:
        lines.append(
            f"| `{row.get('tool', 'unknown')}` | {float(row.get('duration_ms', 0) or 0):.2f} | "
            f"{row.get('success')} | `{row.get('bucket', '')}` | `{row.get('service_version', '')}` |"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Analyze Workflow MCP telemetry")
    parser.add_argument("--calls", default=str(DEFAULT_CALLS), help="Path to calls.jsonl")
    parser.add_argument("--output", help="Report path; defaults to Daily/Lint/YYYY-MM-DD-workflow-mcp-metrics.md")
    parser.add_argument("--stdout", action="store_true", help="Print report instead of writing")
    args = parser.parse_args()

    calls_path = Path(args.calls).expanduser()
    rows, malformed = _load_rows(calls_path)
    report = build_report(rows, malformed, calls_path)
    if args.stdout:
        print(report)
        return 0
    output = Path(args.output).expanduser() if args.output else DEFAULT_REPORT_DIR / f"{dt.date.today().isoformat()}-workflow-mcp-metrics.md"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(report + "\n", encoding="utf-8")
    print(f"workflow-mcp metrics report written: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
